import { defaultSchema, type Options as SanitizeSchema } from 'rehype-sanitize'

/**
 * Allow-list for raw HTML inside Markdown (enabled by rehype-raw).
 *
 * Starts from GitHub's own schema — the same rules github.com applies to
 * README HTML — so `<script>`, `<iframe>`, `<style>`, event handlers and
 * `javascript:` URLs are dropped. The Chrome extension renders Markdown from
 * arbitrary sites, so without this a page could run script inside the
 * extension's own origin.
 *
 * Runs right after rehype-raw and BEFORE rehype-slug / rehype-katex, so
 * heading ids and KaTeX's markup (generated by us, not the document) never
 * pass through it. Every addition over GitHub's schema is deliberately narrow.
 */
// Class names the Markdown pipeline itself emits and later steps or our CSS
// rely on. Raw HTML may only use these — an open class list let a document
// reuse the app's own utilities (`fixed inset-0 z-50`) to cover the viewer.
const ALLOWED_CLASS = /^(?:language-[\w+#.-]+|math-inline|math-display|contains-task-list|task-list-item|footnotes|sr-only)$/

// Backlog's &color(fg[, bg]) is the only source of inline styles we need.
// Anything else (position, z-index, inset, ...) could draw over the app.
const COLOR_ONLY_STYLE = /^\s*(?:(?:color|background-color)\s*:\s*[#\w(),.%\s-]+;?\s*)+$/i

export const markdownSanitizeSchema: SanitizeSchema = {
    ...defaultSchema,
    // Keep GitHub's default "user-content-" prefix on id/name: an unprefixed
    // <img name="createElement"> shadows document.createElement and blanks
    // the viewer (DOM clobbering). Heading ids are added after this step by
    // rehype-slug, so the outline and #anchors are unaffected.
    tagNames: [...(defaultSchema.tagNames ?? []), 'u', 'mark', 'abbr', 'center'],
    attributes: {
        ...defaultSchema.attributes,
        '*': [
            ...(defaultSchema.attributes?.['*'] ?? []),
            ['className', ALLOWED_CLASS],
            // Stamped by rehypeLineNumbers (runs before this) for scroll sync.
            'data-line', 'dataLine',
        ],
        span: [...(defaultSchema.attributes?.span ?? []), ['style', COLOR_ONLY_STYLE]],
    },
    protocols: {
        ...defaultSchema.protocols,
        // Inline images (data:image/png;base64,...) are inert inside <img>,
        // and file: lets a local document (Chrome on file://) show its images.
        src: [...(defaultSchema.protocols?.src ?? []), 'data', 'file'],
    },
}
